package com.example.userAccount.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.UUID;
//Unique identifier (this should be automatically generated by the server)
//First name
//Last name
//Email address
//Date and time when his account was created (this should be automatically generated by the server)
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Account {
    private UUID id;
    private String firstName;
    private String lastName;
    private String email;
    private LocalDateTime date;
}

